### ISSUE TITLE
Essentia Locust support for Quantum Jars

### ISSUE THREAD

**Issue by misterfixit** [Tuhljin/Automagy#17] opened 2015-03-24 17:20 UTC
Quantum jars are from technomancy and I would greatly appreciate it if you could include essentia locust support for them.

**Comment by Lyinginbedmon** [comment] 2015-03-27 02:36
Clarification: Quantum Jars from Technomancy are recognised as jars by the Essentia Mirror and Runic Matrix, but not by the Essentia Locus. Their contents are not included in the Locus' tallies and they are not drawn from during extraction via the Essentia Aggregator.

**Comment by Tuhljin** [comment] 2015-03-27 05:03
I attempted to come up with a solution for this entirely on my end and, while it's technically possible, it's kind of wonky. In this case, I believe it would be better if I simply provided an easy way for them to integrate with Automagy. To that end, the next release will include a new interface in [the API](https://github.com/Tuhljin/Automagy/tree/master/src/main/java/tuhljin/automagy/api) called IEssentiaLocusReadable.

**Comment by Mordenkainen** [comment] 2015-03-27 20:03
Could you describe the reason that the jars are hard to read & deal with?

I am looking to try to bring these jars more into alignment with the normal warded jar in the near future, so if the issue is simply due to some issue with the way the jars are implemented, it may end up being fixed by that.

**Comment by Tuhljin** [comment] 2015-03-27 22:44
Well, if they had extended Thaumcraft's TileJarFillable directly instead of your copy of TileJarFillable in your own package, then they would have been supported by the Essentia Locus out of the box. It's true that I could have set up some special code to read the jars as they are specifically, but that solution wouldn't help the next time an addon comes along with a tile that the locus doesn't support.

The only other viable solution I came up with was setting up a whitelist that people could just drop block names into (and I'd by default put your jar in there, thus handling it entirely on my end) similar to how I have a blacklist for Inventarium containers, but as I set out to do that, I ran into issues with the way the locus works that makes it an unsatisfactory solution. I'd prefer that addons instead either extend from TC's TileJarFillable or implement the interface I've provided, [IEssentiaLocusReadable](https://github.com/Tuhljin/Automagy/blob/master/src/main/java/tuhljin/automagy/api/essentia/IEssentiaLocusReadable). (I also recommend implementing the other new one, [IAspectContainerWithMax](https://github.com/Tuhljin/Automagy/blob/master/src/main/java/tuhljin/automagy/api/essentia/IAspectContainerWithMax) when applicable as that will help vis readers do their thing.)

**Comment by Mordenkainen** [comment] 2015-03-28 00:56
Ok, thanks for the info. I figured that this was the case.

I'm not sure why a private copy of TileJarFillable was used, but this is not the first case where it has caused an issue.

I believe the long term plan is to re-implement the Quantum Jar as a subclass of TileJarFillable, which would also include using it's standard max value field. It sounds like this would likely resolve the issue.

That said, the interfaces are a nice thing to have since there are some other things that "store" essentia that it would not be appropriate to make extend TileJarFillable, and the interfaces should neatly deal with that.

**Comment by Tuhljin** [comment] 2015-03-30 06:25
Closing, as this is apparently going to be handled on Technomancy's end.

**Closed by Tuhljin** 2015-03-30 06:25 UTC
