### ISSUE TITLE
Occasional crash with unseen scribe

### ISSUE THREAD

**Issue by ChaiFox** [Tuhljin/Automagy#16] opened 2015-03-10 00:59 UTC
Minecraft will occasionally crash, should be mentioned that I am using Better Storage crates with the scribe.

java.lang.NullPointerException: Ticking entity
	at tuhljin.automagy.gui.ContainerScribe.getUpdatedItems(ContainerScribe.java:129)
	at tuhljin.automagy.gui.ContainerScribe.func_75142_b(ContainerScribe.java:93)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:212)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Tuhljin** [comment] 2015-03-10 01:29
I need steps to reproduce this. What are you doing when this happens, etc.

**Comment by ChaiFox** [comment] 2015-03-10 01:51
I was standing at the Requisition tome and started to type in an item name and then it crashed. Air shard the first time iron the second. I have the latest version of Thaumcraft, Autoamagy 0.21, I have around 50 other mods though and I've started removing some to see if it is a conflict but it happens randomly .

**Comment by Tuhljin** [comment] 2015-03-11 02:02
I'm still not sure what the root cause of this is but there is a small change I can make that should keep things running smoothly. It will be in the next update.

**Closed** 2015-04-20 23:05 UTC
